# Get
GET http://localhost:4004/odata/v4/dmart/BuyCollection

### POST
POST http://localhost:4004/odata/v4/dmart/BuyCollection 
Content-Type: application/json

{
      "ID": 2,
      "UoM": "KG",
      "category": "Flour",
      "item": "Urad dal",
      "itemInTelugu": "ఉరద్ పప్పు"
    }

#### Get 
GET http://localhost:4004/odata/v4/dmart/MonthlyShoppingList   


##### POST
POST http://localhost:4004/odata/v4/dmart/MonthlyShoppingList 
Content-Type: application/json

{
    
      "item_ID": "2",
      "plannedQuantity"  : 0

}